-- AlterTable
ALTER TABLE "Department" ADD COLUMN     "MARKETING_CREATE" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "MARKETING_DELETE" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "MARKETING_UPDATE" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "MARKETING_VIEW" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "MEDIA" BOOLEAN NOT NULL DEFAULT false;
